/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.DaoClientes;
import javax.swing.JOptionPane;
import model.AblCliente;


/**
 *
 * @author Alisson
 */
public class JDlgAblClientes extends javax.swing.JDialog {

    /**
     
     */
    public JDlgAblClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Clientes");
        setLocationRelativeTo(null);
        desabilitar();
    }
    boolean alterar = false;
    
    public void desabilitar(){
        jTxtAblCodigo.setEnabled(false);
        jTxtAblNome.setEnabled(false);
        jTxtAblEmail.setEnabled(false);
        jFmtAblTelefone.setEnabled(false);
        jFmtAblCpf.setEnabled(false);
        jBtnAblConfirmar.setEnabled(false);
        jBtnAblCancelar.setEnabled(false);
        jBtnAblIncluir.setEnabled(true);
        jBtnAblAlterar.setEnabled(true);
        jBtnAblExcluir.setEnabled(true);
        jBtnAblPesquisar.setEnabled(true);
    }
    
    public void habilitar(){
        jTxtAblCodigo.setEnabled(true);
        jTxtAblNome.setEnabled(true);
        jTxtAblEmail.setEnabled(true);
        jFmtAblTelefone.setEnabled(true);
        jFmtAblCpf.setEnabled(true);
        jBtnAblConfirmar.setEnabled(true);
        jBtnAblCancelar.setEnabled(true);
        jBtnAblIncluir.setEnabled(false);
        jBtnAblAlterar.setEnabled(false);
        jBtnAblExcluir.setEnabled(false);
        jBtnAblPesquisar.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jBtnAblExcluir = new javax.swing.JButton();
        jBtnAblConfirmar = new javax.swing.JButton();
        jBtnAblPesquisar = new javax.swing.JButton();
        jBtnAblCancelar = new javax.swing.JButton();
        jBtnAblIncluir = new javax.swing.JButton();
        jBtnAblAlterar = new javax.swing.JButton();
        jLblCodigo = new javax.swing.JLabel();
        jTxtAblCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtAblNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtAblCpf = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtAblEmail = new javax.swing.JTextField();
        jFmtAblTelefone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("Telefone");

        jBtnAblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnAblExcluir.setText("Excluir");
        jBtnAblExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblExcluirActionPerformed(evt);
            }
        });

        jBtnAblConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnAblConfirmar.setText("Confirmar");
        jBtnAblConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblConfirmarActionPerformed(evt);
            }
        });

        jBtnAblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnAblPesquisar.setText("Pesquisar");
        jBtnAblPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblPesquisarActionPerformed(evt);
            }
        });

        jBtnAblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnAblCancelar.setText("Cancelar");
        jBtnAblCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblCancelarActionPerformed(evt);
            }
        });

        jBtnAblIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnAblIncluir.setText("Incluir");
        jBtnAblIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblIncluirActionPerformed(evt);
            }
        });

        jBtnAblAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAblAlterar.setText("Alterar");
        jBtnAblAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblAlterarActionPerformed(evt);
            }
        });

        jLblCodigo.setText("Código");

        jTxtAblCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAblCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jTxtAblNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAblNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        jFmtAblCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtAblCpfActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        jTxtAblEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAblEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtAblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtAblNome, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel4))
                                            .addComponent(jFmtAblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addComponent(jTxtAblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFmtAblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnAblIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAblAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAblExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAblConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAblCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnAblPesquisar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtAblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtAblNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtAblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtAblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtAblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAblIncluir)
                    .addComponent(jBtnAblAlterar)
                    .addComponent(jBtnAblExcluir)
                    .addComponent(jBtnAblConfirmar)
                    .addComponent(jBtnAblPesquisar)
                    .addComponent(jBtnAblCancelar))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAblExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblExcluirActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(
               JOptionPane.showInputDialog(null, "Entre com o ID do usuario"));
        
        DaoClientes dao =  new DaoClientes();
        AblCliente cliente = (AblCliente) dao.list(id);
        
        if(cliente!=null){//encontrou no bd
            int resp = JOptionPane.showConfirmDialog(null, "Deseja Excluir",
                    "confirma", JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION){
                dao.delete(cliente);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
        }  
        
    }//GEN-LAST:event_jBtnAblExcluirActionPerformed

    private void jBtnAblConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblConfirmarActionPerformed
        desabilitar();        // TODO add your handling code here:
        // TODO add your handling code here:
AblCliente cliente = new AblCliente();

//cliente.setId_cliente(Integer.parseInt(jTxtCodigo.getText()));
cliente.setNome(jTxtAblNome.getText());
cliente.setCpf(jFmtAblCpf.getText());
cliente.setEmail(jTxtAblEmail.getText());
cliente.setTelefone(jFmtAblTelefone.getText());


DaoClientes dao = new DaoClientes();

if (!alterar) {
    if (dao.insert(cliente)) {
        JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar cliente!");
    }
} else { // alterar está verdadeiro
    cliente.setId_cliente(Integer.parseInt(jTxtAblCodigo.getText()));
   
        cliente.setId_cliente(Integer.parseInt(jTxtAblCodigo.getText()));

        dao.update(cliente);

        JOptionPane.showMessageDialog(this, "Cliente alterado com sucesso!");
    }


        desabilitar();
        alterar = false;
    }//GEN-LAST:event_jBtnAblConfirmarActionPerformed

    private void jBtnAblPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgAblClienteList Listar = new JDlgAblClienteList(null, true);
        Listar.setVisible(true);
    }//GEN-LAST:event_jBtnAblPesquisarActionPerformed

    private void jBtnAblCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnAblCancelarActionPerformed

    private void jBtnAblIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnAblIncluirActionPerformed

    private void jBtnAblAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblAlterarActionPerformed
         alterar = true;
    habilitar();
    int id = Integer.parseInt(
        JOptionPane.showInputDialog(null, "Entre com o ID do cliente"));

DaoClientes dao = new DaoClientes();
AblCliente cliente = (AblCliente) dao.list(id);

if (cliente != null) { // encontrou no banco
    jTxtAblCodigo.setText(String.valueOf(cliente.getId_cliente()));
    jTxtAblNome.setText(cliente.getNome());
    jFmtAblCpf.setText(cliente.getCpf());
    jTxtAblEmail.setText(cliente.getEmail());
    jFmtAblTelefone.setText(cliente.getTelefone());
    
}// TODO add your handling code here:
    }//GEN-LAST:event_jBtnAblAlterarActionPerformed

    private void jTxtAblCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAblCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAblCodigoActionPerformed

    private void jTxtAblNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAblNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAblNomeActionPerformed

    private void jTxtAblEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAblEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAblEmailActionPerformed

    private void jFmtAblCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtAblCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtAblCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgAblClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgAblClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgAblClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgAblClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgAblClientes dialog = new JDlgAblClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAblAlterar;
    private javax.swing.JButton jBtnAblCancelar;
    private javax.swing.JButton jBtnAblConfirmar;
    private javax.swing.JButton jBtnAblExcluir;
    private javax.swing.JButton jBtnAblIncluir;
    private javax.swing.JButton jBtnAblPesquisar;
    private javax.swing.JFormattedTextField jFmtAblCpf;
    private javax.swing.JFormattedTextField jFmtAblTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JTextField jTxtAblCodigo;
    private javax.swing.JTextField jTxtAblEmail;
    private javax.swing.JTextField jTxtAblNome;
    // End of variables declaration//GEN-END:variables
}
