/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import dao.DaoProduto;
import model.AblProduto;



/**
 *
 * @author Alisson
 */
public class JDlgAblProdutos extends javax.swing.JDialog {
    boolean alterar = false;
    /**
     * Creates new form JDlgProdutos
     */
    public JDlgAblProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Produtos");
        setLocationRelativeTo(null);
        desabilitar();
    }
    
    public void desabilitar(){
        jTxtAblCodigo.setEnabled(false);
        jTxtAblDescricao.setEnabled(false);
        jTxtAblUnidade.setEnabled(false);
        jTxtAblTipo.setEnabled(false);
        jFmtAblPreco.setEnabled(false);
        jBtnAblConfirmar.setEnabled(false);
        jBtnAblCancelar.setEnabled(false);
        jBtnAblIncluir.setEnabled(true);
        jBtnAblAlterar.setEnabled(true);
        jBtnAblExcluir.setEnabled(true);
        jBtnAblPesquisar.setEnabled(true);
    }
    
    public void habilitar(){
        jTxtAblCodigo.setEnabled(true);
        jTxtAblDescricao.setEnabled(true);
        jTxtAblUnidade.setEnabled(true);
        jTxtAblTipo.setEnabled(true);
        jFmtAblPreco.setEnabled(true);
        jBtnAblConfirmar.setEnabled(true);
        jBtnAblCancelar.setEnabled(true);
        jBtnAblIncluir.setEnabled(false);
        jBtnAblAlterar.setEnabled(false);
        jBtnAblExcluir.setEnabled(false);
        jBtnAblPesquisar.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtAblDescricao = new javax.swing.JTextField();
        jBtnAblConfirmar = new javax.swing.JButton();
        jTxtAblTipo = new javax.swing.JTextField();
        jBtnAblPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnAblCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtAblUnidade = new javax.swing.JTextField();
        jFmtAblPreco = new javax.swing.JFormattedTextField();
        jLblCodigo = new javax.swing.JLabel();
        jBtnAblIncluir = new javax.swing.JButton();
        jTxtAblCodigo = new javax.swing.JTextField();
        jBtnAblAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnAblExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxtAblDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAblDescricaoActionPerformed(evt);
            }
        });

        jBtnAblConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnAblConfirmar.setText("Confirmar");
        jBtnAblConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblConfirmarActionPerformed(evt);
            }
        });

        jTxtAblTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAblTipoActionPerformed(evt);
            }
        });

        jBtnAblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnAblPesquisar.setText("Pesquisar");
        jBtnAblPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo");

        jBtnAblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnAblCancelar.setText("Cancelar");
        jBtnAblCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Unidade");

        jLabel3.setText("Preço");

        jFmtAblPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtAblPrecoActionPerformed(evt);
            }
        });

        jLblCodigo.setText("Código");

        jBtnAblIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnAblIncluir.setText("Incluir");
        jBtnAblIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblIncluirActionPerformed(evt);
            }
        });

        jBtnAblAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAblAlterar.setText("Alterar");
        jBtnAblAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblAlterarActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrição");

        jBtnAblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnAblExcluir.setText("Excluir");
        jBtnAblExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAblExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtAblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtAblDescricao)))
                    .addComponent(jTxtAblTipo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtAblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jFmtAblPreco)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnAblIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAblAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAblExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAblConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAblCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAblPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtAblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAblIncluir)
                    .addComponent(jBtnAblAlterar)
                    .addComponent(jBtnAblExcluir)
                    .addComponent(jBtnAblConfirmar)
                    .addComponent(jBtnAblPesquisar)
                    .addComponent(jBtnAblCancelar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtAblDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAblDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAblDescricaoActionPerformed

    private void jBtnAblConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblConfirmarActionPerformed
        desabilitar(); 
        // TODO add your handling code here:
        AblProduto produto = new AblProduto();

    produto.setDescricao(jTxtAblDescricao.getText());
    produto.setTipo(jTxtAblTipo.getText());
    produto.setUnidade(jTxtAblUnidade.getText());
    produto.setPreco(Double.parseDouble(jFmtAblPreco.getText()));

    DaoProduto dao = new DaoProduto();

    if (!alterar) {

        if (dao.insert(produto)) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto!");
        }

    } else {

        produto.setId_produto(Integer.parseInt(jTxtAblCodigo.getText()));

        dao.update(produto);

        JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!");
    }

    desabilitar();
    alterar = false;

    }//GEN-LAST:event_jBtnAblConfirmarActionPerformed

    private void jTxtAblTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAblTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAblTipoActionPerformed

    private void jBtnAblPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgAblProdutoList telaListar = new JDlgAblProdutoList(null, true);
        telaListar.setVisible(true);
    }//GEN-LAST:event_jBtnAblPesquisarActionPerformed

    private void jBtnAblCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnAblCancelarActionPerformed

    private void jFmtAblPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtAblPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtAblPrecoActionPerformed

    private void jBtnAblIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
        
    }//GEN-LAST:event_jBtnAblIncluirActionPerformed

    private void jBtnAblAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblAlterarActionPerformed
        habilitar();        // TODO add your handling code here:
        alterar = true;
    habilitar();

    int id = Integer.parseInt(
            JOptionPane.showInputDialog(null, "Entre com o ID do produto"));

    DaoProduto dao = new DaoProduto();

    AblProduto produto = (AblProduto) dao.list(id);

    if (produto != null) {

        jTxtAblCodigo.setText(String.valueOf(produto.getId_produto()));
        jTxtAblDescricao.setText(produto.getDescricao());
        jTxtAblTipo.setText(produto.getTipo());
        jTxtAblUnidade.setText(produto.getUnidade());
        jFmtAblPreco.setText(String.valueOf(produto.getPreco()));

    } else {

        JOptionPane.showMessageDialog(this, "Produto não encontrado!");
        desabilitar();
        alterar = false;
    }
    }//GEN-LAST:event_jBtnAblAlterarActionPerformed

    private void jBtnAblExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAblExcluirActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(
            JOptionPane.showInputDialog(null, "Entre com o ID do produto"));

    DaoProduto dao = new DaoProduto();
    AblProduto produto = (AblProduto) dao.list(id);

    if (produto != null) {

        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja excluir o produto?",
                "Confirma",
                JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_OPTION) {
            dao.delete(produto);
            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
        }

    } else {

        JOptionPane.showMessageDialog(this, "Produto não encontrado!");
    }
    }//GEN-LAST:event_jBtnAblExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgAblProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgAblProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgAblProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgAblProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgAblProdutos dialog = new JDlgAblProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAblAlterar;
    private javax.swing.JButton jBtnAblCancelar;
    private javax.swing.JButton jBtnAblConfirmar;
    private javax.swing.JButton jBtnAblExcluir;
    private javax.swing.JButton jBtnAblIncluir;
    private javax.swing.JButton jBtnAblPesquisar;
    private javax.swing.JFormattedTextField jFmtAblPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JTextField jTxtAblCodigo;
    private javax.swing.JTextField jTxtAblDescricao;
    private javax.swing.JTextField jTxtAblTipo;
    private javax.swing.JTextField jTxtAblUnidade;
    // End of variables declaration//GEN-END:variables
}
